import { BaseModel } from '../BaseModel';
import { VoucherCodeStatus } from './../Vouchers/VoucherCodeStatus';
interface IPromotionVoucherData {
    code: string;
    status: string;
    autoGenerated: boolean;
    lastingAt?: number;
    redeemedAt?: number;
    assignedAt: number;
}
declare class PromotionVoucherData extends BaseModel {
    code: string;
    status: VoucherCodeStatus;
    autoGenerated: boolean;
    assignedAt: Date;
    lastingAt?: Date;
    redeemedAt?: Date;
    constructor(modelObject: IPromotionVoucherData);
}
export { IPromotionVoucherData, PromotionVoucherData };
