"use strict";
var __extends = (this && this.__extends) || (function () {
    var extendStatics = function (d, b) {
        extendStatics = Object.setPrototypeOf ||
            ({ __proto__: [] } instanceof Array && function (d, b) { d.__proto__ = b; }) ||
            function (d, b) { for (var p in b) if (b.hasOwnProperty(p)) d[p] = b[p]; };
        return extendStatics(d, b);
    };
    return function (d, b) {
        extendStatics(d, b);
        function __() { this.constructor = d; }
        d.prototype = b === null ? Object.create(b) : (__.prototype = b.prototype, new __());
    };
})();
Object.defineProperty(exports, "__esModule", { value: true });
exports.PromotionVoucherData = void 0;
var BaseModel_1 = require("../BaseModel");
var VoucherCodeStatus_1 = require("./../Vouchers/VoucherCodeStatus");
var PromotionVoucherData = /** @class */ (function (_super) {
    __extends(PromotionVoucherData, _super);
    function PromotionVoucherData(modelObject) {
        var _this = _super.call(this, modelObject) || this;
        _this.code = modelObject.code;
        _this.status = VoucherCodeStatus_1.VoucherCodeStatusFromString(modelObject.status);
        _this.autoGenerated = modelObject.autoGenerated;
        _this.assignedAt = new Date(modelObject.assignedAt * 1000);
        if (modelObject.lastingAt !== undefined && modelObject.lastingAt != null) {
            _this.lastingAt = new Date(modelObject.lastingAt * 1000);
        }
        if (modelObject.redeemedAt !== undefined && modelObject.redeemedAt != null) {
            _this.redeemedAt = new Date(modelObject.redeemedAt * 1000);
        }
        return _this;
    }
    return PromotionVoucherData;
}(BaseModel_1.BaseModel));
exports.PromotionVoucherData = PromotionVoucherData;
